resilience4j:
  retry:
    instances:
      directFallback:
        max-attempts: 1
        wait-duration: 0s
  circuitbreaker:
    instances:
      spring:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 6
        minimum-number-of-calls: 3
  ratelimiter:
    instances:
      spring:
        limit-for-period: 4
        timeout-duration: 5s
        limit-refresh-period: 10s

management:
  endpoints:
    web:
      exposure:
        include: '*'
