resilience4j:
  retry:
    instances:
      directFallback:
        max-attempts: 1
        wait-duration: 0s
      spring:
        max-attempts: 3
        wait-duration: 200ms
  circuitbreaker:
    instances:
      spring:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 6
        minimum-number-of-calls: 3
  ratelimiter:
    instances:
      spring:
        limit-for-period: 4
        timeout-duration: 5s
        limit-refresh-period: 10s
  timelimiter:
    instances:
      spring:
        timeout-duration: 5s
        cancel-running-future: true
  bulkhead:
    instances:
      spring:
        max-concurrent-calls: 4
        max-wait-duration: 4s

management:
  endpoints:
    web:
      exposure:
        include: '*'
